### ISSUE TITLE
What is the correct way to get data from m2m relationship with extra fields?

### ISSUE THREAD

**Issue by dimuska139** [go-gorm/gorm#2508]
### What version of Go are you using (`go version`)?
go version go1.12.5 linux/amd64

### Which database and its version are you using?
Postgres 11.2

I want to get images (struct with name "File") with related thumbnails (Thumbnail struct). Thumbnails and original images stores in common table - Files. Thumbnails table contains relations to source and thumnails. Also it contains extra field "type". I don't understand why Gorm generates incorrect sql query string.

docker-compose.yml:
```yml
version: '2'

services:
  db:
    image: postgres:11.2
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    ports:
      - 735:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=photos
      - PGDATA=/var/lib/postgresql/data/pgdata
```
```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

type File struct {
	ID          uint         `gorm:"primary_key"`
	Path        string       `gorm:"not null;column:path;type:text"`
	Filename    string       `gorm:"not null;column:filename;varchar(200)"`
	Description string       `gorm:"not null;column:description;type:text"`
	Size        uint         `gorm:"not null;column:size;type:int"`
	OwnerId     uint         `gorm:"not null;column:owner_id;type:int"`
	ContentType string       `gorm:"not null;column:type;type:varchar(100)"`
	Meta        string       `gorm:"column:meta;type:json"`
	Thumbnails  []*Thumbnail `gorm:"many2many:common_image_thumbnails;association_jointable_foreignkey:file_id"`
}

func (File) TableName() string {
	return "common_file"
}

type Thumbnail struct {
	File        *File  `gorm:"foreignkey:id;association_foreignkey:file_id"`
	FileID      int    `gorm:"not null;column:file_id;type:int"`
	Thumbnail   *File  `gorm:"foreignkey:id;association_foreignkey:thumbnail_id"`
	ThumbnailID int    `gorm:"not null;column:thumbnail_id;type:int"`
	Type        string `gorm:"not null;column:type;type:varchar(50)"`
}

func (*Thumbnail) TableName() string {
	return "common_image_thumbnails"
}

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("postgres", "user=user password=12345 DB.name=photos port=735 sslmode=disable")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
        var files []File
	if err := db.Model(&File{}).Preload("Thumbnails.Thumbnail").Order("id desc").Find(&files).Error; err != nil {
            panic(err)
        }
}
```
In this case Gorm makes tho sql queries:
_SELECT * FROM "common_file"   ORDER BY id desc_
and
_SELECT * FROM "common_image_thumbnails" INNER JOIN "common_image_thumbnails" ON  WHERE (1 <> 1)_

Second query is not valid and pg returns error: **Error #01: pq: syntax error at or near "WHERE"**.
