### ISSUE TITLE
执行create后，返回的MySQL主键值不对

### ISSUE THREAD

**Issue by OMG-By** [go-gorm/gorm#4657]
## GORM Playground Link
https://github.com/go-gorm/playground/pull/1

### 环境
gorm版本：`github.com/jinzhu/gorm v1.9.10`
MySQL版本：`5.5.24、5.7.18`
struct:
```
type JobQueue struct {
	Uid int64 `gorm:"column:uid;AUTO_INCREMENT" db:"column:uid" json:"uid" form:"uid"`
	Username string `gorm:"column:username" db:"column:username" json:"username" form:"username"`
	App string `gorm:"column:app" db:"column:app" json:"app" form:"app"`
	Input string `gorm:"column:input" db:"column:input" json:"input" form:"input"`
	Status string `gorm:"column:status" db:"column:status" json:"status" form:"status"`
	Name string `gorm:"column:name" db:"column:name" json:"name" form:"name"`
	SubjobDone int64 `gorm:"column:subjob_done" db:"column:subjob_done" json:"subjob_done" form:"subjob_done"`
	SubjobUndone int64 `gorm:"column:subjob_undone" db:"column:subjob_undone" json:"subjob_undone" form:"subjob_undone"`
	SubjobSucc int64 `gorm:"column:subjob_succ" db:"column:subjob_succ" json:"subjob_succ" form:"subjob_succ"`
	SubjobFail int64 `gorm:"column:subjob_fail" db:"column:subjob_fail" json:"subjob_fail" form:"subjob_fail"`
	TagId int64 `gorm:"column:tag_id" db:"column:tag_id" json:"tag_id" form:"tag_id"`
}
```
表结构:
```
CREATE TABLE `job_queue` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(32) DEFAULT NULL,
  `app` varchar(32) DEFAULT NULL,
  `input` longtext,
  `status` varchar(16) DEFAULT 'start',
  `name` varchar(64) DEFAULT NULL,
  `subjob_done` int(11) DEFAULT '0',
  `subjob_undone` int(11) DEFAULT '0',
  `subjob_succ` int(11) DEFAULT '0',
  `subjob_fail` int(11) DEFAULT '0',
  `tag_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`uid`),
  KEY `ind_billid` (`tag_id`),
  KEY `idx_s` (`status`,`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=2085427 DEFAULT CHARSET=utf8
```
表里有一条初始数据：
```
MySQL > select * from job_queue\G
*************************** 1. row ***************************
          uid: 3333
     username: xxxx
          app: pub
        input: 
       status: done
         name: namexx
  subjob_done: 0
subjob_undone: 0
  subjob_succ: 1
  subjob_fail: 0
       tag_id: 47
```

### 操作
```
Job := &JobQueue{}
Job.Name = "xxxxx"
Job.App = "pub"
Job.Username = "user"
Job.Status = "start"
Job.Input = "jobInput"

db.Create(t)
fmt.Sprint("uid[%d]", Job.Uid)
```

在执行完`create`操作后，输出的uid为`3333`。

-----
经过排查，发现是gorm在执行完insert后，会执行一条`SELECT uid FROM job_queue;`语句去查询uid最大值。不过在MySQL中，走的是`ind_billid`索引。导致查询出来的结果顺序不对，进而返回的uid不对。
```
MySQL> explain SELECT `uid` FROM `job_queue`\G
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: job_queue
   partitions: NULL
         type: index
possible_keys: NULL
          key: ind_billid
      key_len: 4
          ref: NULL
         rows: 2
     filtered: 100.00
        Extra: Using index
```
